wip_limit: 1                    # Strict capacity: 1 ticket max per engineer
sprint_duration_days: 20
jira_project_key: "KAN"         # Swap this out with your exact live Jira project key
confidence_threshold: 0.60

teams:
  - name: "FRONTEND"
    slack_channel: ""           # Empty string since we are skipping Slack for now
    engineers:
      - name: "Aniket Pathak"
        jira_account_id: "712020:c8455f75-d3f1-4ed0-8a3f-e724935eaee7"
        slack_user_id: ""
      - name: "Ayush Mittal"
        jira_account_id: "712020:856bc8f8-1e57-4b4b-8fef-dfff217ae341"
        slack_user_id: ""