confidence_threshold: 0.6
jira_project_key: KAN
sprint_duration_days: 20
teams:
- engineers:
  - github_username: Aniket-bit7
    is_team_lead: false
    jira_account_id: 712020:c8455f75-d3f1-4ed0-8a3f-e724935eaee7
    name: Aniket Pathak
    slack_user_id: ''
  - github_username: ayush-mittal
    is_team_lead: false
    jira_account_id: 712020:856bc8f8-1e57-4b4b-8fef-dfff217ae341
    name: Ayush Mittal
    slack_user_id: ''
  name: FRONTEND
  slack_channel: ''
  team_lead_slack_id: U_TEST_LEAD_123
wip_limit: 1
